### ISSUE TITLE
Facebook videos links are not working 

### ISSUE THREAD

**Issue by ubaidakmal** [thitlwincoder/direct_link#25]
I tried to download facebook videos but it returns me empty data I tried many URLs like

https://www.facebook.com/share/v/19UieetVp8/
https://www.facebook.com/share/v/15aC776rea/
https://www.facebook.com/share/r/rJEHKfbLVXbUQYaf/?mibextid=D5vuiz

**Comment by thitlwincoder** [comment]
Can you please provide more details? What platform do you use, and what error do you get? I tried using the URLs you gave me, and that worked.

**Comment by ubaidakmal** [comment]
Hi, hope this , e-mail finds you well, basically I'm using your package to
download Facebook videos using the Facebook videos URL in my Flutter app
but when I pass the URL and press get link button after loading for 5 to 6
sec I get a response like video not found.

this is my function

Future<void> getVideoLink(String url) async {
  try {
    var directLink = DirectLink();
    var data = await directLink.check(url).timeout(Duration(seconds: 30));

    if (data != null && data.links != null && data.links!.isNotEmpty) {
      setState(() {
        videoLink = data.links!.first.link;
      });

      print("direct link of facebook video link $videoLink");
      print("direct link of facebook video title ${data.title}");
      print("direct link of facebook video duration ${data.duration}");
      print("direct link of facebook video thumbnail ${data.thumbnail}");
      for (var e in data.links!) {
        print(e.type);
        print(e.quality);
        print('-' * 20);
      }

      showModalBottomSheet(
        context: context,
        isScrollControlled: true,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
        ),
        builder: (context) => downloadVideoBottomSheet(
            context,
            data.thumbnail ??

"https://as2.ftcdn.net/v2/jpg/02/51/95/53/1000_F_251955356_FAQH0U1y1TZw3ZcdPGybwUkH90a3VAhb.jpg",
            data.title ?? "video",
            videoLinks: data.links),
      ).then((_) {
        pasteLink.clear();
        Clipboard.setData(ClipboardData(text: ''));
      });
    } else {
      print("No direct link found or unsupported website.");
    }
  } catch (e) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text("Request timed out. Please try again.")),
    );
    print("Error fetching video link: $e");
  } finally {
    setState(() {
      isLoading = false; // Ensure loading is stopped
    });
  }
}

I get this No direct link found or unsupported website.

**Comment by thitlwincoder** [comment]
I just tested with an example code. This is my result.

https://github.com/user-attachments/assets/c630093d-4708-44de-860f-edf0a3768bdc

**Comment by ubaidakmal** [comment]
Can you please share your example code ?

**Comment by thitlwincoder** [comment]
Sure. I just call with
```dart
DirectLink().check('url');
```
You can also see the github example project. I recommend testing with this example project.

**Comment by ubaidakmal** [comment]
it works for Facebook public video only, is there any way to download
private videos also

**Comment by thitlwincoder** [comment]
If you want to download private videos, we have a way of scraping them, but they can't be used directly. a better way is to use with webview.
