### ISSUE TITLE
Nothing Works

### ISSUE THREAD

**Issue by OttomanDeveloper** [thitlwincoder/direct_link#6]
I Try this Package today but unfortunately, nothing works. Facebook, Instagram, Google Drive

**Comment by thitlwincoder** [comment]
Sorry for that, I'll fix it

**Comment by Ali540g** [comment]
>

**Comment by Ali540g** [comment]
if (check == null) {
    // null condition
}else{
    check.forEach((e) {
      print(e.quality);
      print(e.link);
    });
}

**Comment by shinewanna** [comment]
Not work for most case, only work for few case. I don't know why is the reason, it returning null or throw exception.

**Comment by beevers** [comment]
the value is null

**Comment by thitlwincoder** [comment]
You can use latest version. Now I already fixed this
