### ISSUE TITLE
facebook link issue

### ISSUE THREAD

**Issue by mhdaslam790** [thitlwincoder/direct_link#8]
hy 
it is not working for all type of facebook video link 
ex : https://m.facebook.com/story.php?story_fbid=481008509351664&id=161276981324820&fs=60&focus_composer=0&m_entstream_source=video_home&player_suborigin=feed&player_format=permalink

above link returns null

**Comment by thitlwincoder** [comment]
you can use only video link

**Comment by shinewanna** [comment]
video link also not work for many case

**Comment by thitlwincoder** [comment]
You can use latest version. Now I already fixed this
