### ISSUE TITLE
Cors Flutter Web

### ISSUE THREAD

**Issue by Dansp** [thitlwincoder/direct_link#9]
There is problem with cors in Flutter Web. In debugger I get this XMLHttpRequest error.

**Comment by Saifallak** [comment]
checkout: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
and also: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

this has nothing to be done in flutter.

as this is resource sharing from the site you're trying to fetch from. and all browsers respect this rule.

the only way to bypass this is by using proxy server in the middle.

**Comment by thitlwincoder** [comment]
@Dansp Try with latest version.
